Traceback (most recent call last):
  File "C:\Users\amekn\Desktop\DSA\Project3\output.cgi", line 12, in <module>
    from graph.main import *
  File "C:\Users\amekn\Desktop\DSA\Project3\graph\main.py", line 7, in <module>
    network = graph()
              ^^^^^^^
TypeError: 'module' object is not callable
